export const ErrorCodes = {
    SESSION_MISSING: 'SESSION_MISSING',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_MISMATCH: 'SESSION_MISMATCH',
    JOIN_TOKEN_REQUIRED: 'JOIN_TOKEN_REQUIRED',
    JOIN_TOKEN_INVALID: 'JOIN_TOKEN_INVALID',
    JOIN_TOKEN_EXPIRED: 'JOIN_TOKEN_EXPIRED',
    ROOM_FULL: 'ROOM_FULL',
    MATCH_ALREADY_STARTED: 'MATCH_ALREADY_STARTED',
    ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
    SEAT_SWITCH_DISABLED: 'SEAT_SWITCH_DISABLED',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
