// src/models/GameEnums.ts
// Game enumerations for custom trading card game

export enum GamePhase {
    WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
    BOTH_JOINED = 'BOTH_JOINED',
    READY_PHASE = 'READY_PHASE',
    START_REDRAW = 'START_REDRAW',
    REDRAW_PHASE = 'REDRAW_PHASE',
    DRAW_PHASE = 'DRAW_PHASE',
    RESOURCE_PHASE = 'RESOURCE_PHASE',
    MAIN_PHASE = 'MAIN_PHASE',
    ATTACK_PHASE = 'ATTACK_PHASE',
    BLOCK_PHASE = 'BLOCK_PHASE',
    DAMAGE_PHASE = 'DAMAGE_PHASE',
    END_PHASE = 'END_PHASE'
}

export enum ZoneType {
    SLOT1 = 'slot1',
    SLOT2 = 'slot2',
    SLOT3 = 'slot3',
    SLOT4 = 'slot4',
    SLOT5 = 'slot5',
    SLOT6 = 'slot6',
    BASE = 'base',
    SHIELD = 'shield'
}

export enum ActionType {
    PLAY_UNIT = 'PLAY_UNIT',
    PLAY_PILOT = 'PLAY_PILOT', 
    PLAY_COMMAND = 'PLAY_COMMAND',
    PLAY_BASE = 'PLAY_BASE',
    PLAY_SHIELD = 'PLAY_SHIELD',
    PAIR_PILOT = 'PAIR_PILOT',
    ACTIVATE_ABILITY = 'ACTIVATE_ABILITY',
    ATTACK = 'ATTACK',
    BLOCK = 'BLOCK',
    REST_CARD = 'REST_CARD',
    APPLY_EFFECT = 'APPLY_EFFECT'
}

export enum EventType {
    ROOM_CREATED = 'ROOM_CREATED',
    GAME_STARTED = 'GAME_STARTED',
    GAME_CREATED = 'GAME_CREATED',
    INITIAL_HAND_DEALT = 'INITIAL_HAND_DEALT',
    PLAYER_JOINED = 'PLAYER_JOINED',
    PLAYER_READY = 'PLAYER_READY',
    HAND_REDRAWN = 'HAND_REDRAWN',
    CARD_PLAYED = 'CARD_PLAYED',
    CARD_DRAWN = 'CARD_DRAWN',
    ZONE_FILLED = 'ZONE_FILLED',
    PHASE_CHANGE = 'PHASE_CHANGE',
    TURN_SWITCH = 'TURN_SWITCH',
    ERROR_OCCURRED = 'ERROR_OCCURRED',
    UNITS_DEPLOYED = 'UNITS_DEPLOYED',
    PILOT_PAIRED = 'PILOT_PAIRED',
    ATTACK_DECLARED = 'ATTACK_DECLARED',
    BLOCK_DECLARED = 'BLOCK_DECLARED',
    DAMAGE_DEALT = 'DAMAGE_DEALT',
    UNIT_DESTROYED = 'UNIT_DESTROYED',
    ABILITY_ACTIVATED = 'ABILITY_ACTIVATED',
    DRAW_PHASE_COMPLETE = 'DRAW_PHASE_COMPLETE',
    GAME_PHASE_START = 'GAME_PHASE_START',
    CARD_SELECTION_REQUIRED = 'CARD_SELECTION_REQUIRED',
    CARD_MOVED_TO_HAND = 'CARD_MOVED_TO_HAND'
}