// src/types/ChoiceKind.ts
// Shared "what is this choice asking the player to do?" indicator for choice notifications.

export enum ChoiceKind {
    EFFECT_TARGET_CHOICE = 'EFFECT_TARGET_CHOICE',

    DISCARD_FROM_HAND = 'DISCARD_FROM_HAND',
    MOVE_FROM_HAND_TO_DECK_BOTTOM = 'MOVE_FROM_HAND_TO_DECK_BOTTOM',
    MOVE_FROM_TRASH_TO_DECK = 'MOVE_FROM_TRASH_TO_DECK',
    EXILE_FROM_TRASH = 'EXILE_FROM_TRASH',

    DESTROY = 'DESTROY',
    RETURN_TO_HAND = 'RETURN_TO_HAND',
    ADD_TO_HAND = 'ADD_TO_HAND',

    REST = 'REST',
    SET_ACTIVE = 'SET_ACTIVE',
    RESTRICT_ATTACK = 'RESTRICT_ATTACK',
    PREVENT_BATTLE_DAMAGE = 'PREVENT_BATTLE_DAMAGE',
    PREVENT_SET_ACTIVE_NEXT_TURN = 'PREVENT_SET_ACTIVE_NEXT_TURN',
    ALLOW_ATTACK_TARGET = 'ALLOW_ATTACK_TARGET',

    DAMAGE = 'DAMAGE',
    DAMAGE_SHIELD = 'DAMAGE_SHIELD',
    HEAL = 'HEAL',

    DEPLOY_FROM_HAND = 'DEPLOY_FROM_HAND',
    PAIR_FROM_TRASH = 'PAIR_FROM_TRASH',

    GRANT_KEYWORD = 'GRANT_KEYWORD',
    GRANT_BREACH = 'GRANT_BREACH',
    PREVENT_SHIELD_DAMAGE = 'PREVENT_SHIELD_DAMAGE',
    SCRY_TOP_DECK = 'SCRY_TOP_DECK',
    ADD_BASIC_ENERGY = 'ADD_BASIC_ENERGY',
    ADD_EXTRA_ENERGY = 'ADD_EXTRA_ENERGY',
    CONDITIONAL_TOKEN_DEPLOY = 'CONDITIONAL_TOKEN_DEPLOY'
}

export function isSequenceContextKind(kind: unknown): boolean {
    return typeof kind === 'string' && kind.startsWith('SEQUENCE_');
}

